version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./data:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     volumes: 
      - wp_data:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_CONFIG_EXTRA: |
               define('WP_HOME','http://45.79.210.227');
               define('WP_SITEURL','http://45.79.210.227');

  wpcli:
      depends_on: 
        - mysql
        - wordpress
      image: wordpress:cli
      links:
        - mysql:db
      volumes:
        - wp_data:/var/www/html/wp-content

volumes:
  db_data:
  wp_data: