# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            # Remove repo dir if exists
            rm -rf ceic_wordpress
            git clone https://github.com/Code-For-Chicago/ceic_wordpress.git
            cd ceic_wordpress
            
            #build container
            #command to build 
            #docker build -t [CONTAINER]:latest . --no-cache
            
            # stop all running containers
            #docker stop $(docker ps -aq) 
            
            # run container
            #docker run -d -p [PORT] [CONTAINER
